set(${PROJECT_NAME}_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src)
set(${PROJECT_NAME}_HEADER_DIR ${CMAKE_CURRENT_SOURCE_DIR}/include)
set(${PROJECT_NAME}_EXAMPLE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/example/src)
set(${PROJECT_NAME}_TEST_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/test/src)

file(GLOB_RECURSE ${PROJECT_NAME}_SOURCES ${${PROJECT_NAME}_SOURCE_DIR}/*.c)
file(GLOB_RECURSE ${PROJECT_NAME}_HEADERS ${${PROJECT_NAME}_HEADER_DIR}/*.h)
file(GLOB_RECURSE ${PROJECT_NAME}_EXAMPLE_SOURCES ${${PROJECT_NAME}_EXAMPLE_SOURCE_DIR}/*.c)
file(GLOB_RECURSE ${PROJECT_NAME}_TEST_SOURCES ${${PROJECT_NAME}_TEST_SOURCE_DIR}/*.cpp)